
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;
	private global::Gtk.Action FetchAction;
	private global::Gtk.Action refreshAction;
	private global::Gtk.VBox vbox1;
	private global::Gtk.MenuBar menubar1;
	private global::Gtk.ScrolledWindow GtkScrolledWindow;
	private global::Gtk.TreeView TreeView;
	private global::Gtk.HPaned hpaned1;
	private global::Gtk.Entry InputAuthor;
	private global::Gtk.Button AuthorBtn;
	
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager ();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
		this.FetchAction = new global::Gtk.Action ("FetchAction", global::Mono.Unix.Catalog.GetString ("Fetch"), null, null);
		this.FetchAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Fetch");
		w1.Add (this.FetchAction, null);
		this.refreshAction = new global::Gtk.Action ("refreshAction", global::Mono.Unix.Catalog.GetString ("Net"), null, "gtk-refresh");
		this.refreshAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Net");
		w1.Add (this.refreshAction, "<Primary><Mod2>n");
		this.UIManager.InsertActionGroup (w1, 0);
		this.AddAccelGroup (this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.Icon = global::Stetic.IconLoader.LoadIcon (this, "gtk-no", global::Gtk.IconSize.Menu);
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString ("<ui><menubar name='menubar1'><menu name='FetchAction' action='FetchAction'><menuitem name='refreshAction' action='refreshAction'/></menu></menubar></ui>");
		this.menubar1 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/menubar1")));
		this.menubar1.Name = "menubar1";
		this.vbox1.Add (this.menubar1);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.menubar1]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.TreeView = new global::Gtk.TreeView ();
		this.TreeView.CanFocus = true;
		this.TreeView.Name = "TreeView";
		this.GtkScrolledWindow.Add (this.TreeView);
		this.vbox1.Add (this.GtkScrolledWindow);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.GtkScrolledWindow]));
		w4.Position = 1;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hpaned1 = new global::Gtk.HPaned ();
		this.hpaned1.CanFocus = true;
		this.hpaned1.Name = "hpaned1";
		this.hpaned1.Position = 667;
		// Container child hpaned1.Gtk.Paned+PanedChild
		this.InputAuthor = new global::Gtk.Entry ();
		this.InputAuthor.CanFocus = true;
		this.InputAuthor.Name = "InputAuthor";
		this.InputAuthor.IsEditable = true;
		this.InputAuthor.InvisibleChar = '●';
		this.hpaned1.Add (this.InputAuthor);
		global::Gtk.Paned.PanedChild w5 = ((global::Gtk.Paned.PanedChild)(this.hpaned1 [this.InputAuthor]));
		w5.Resize = false;
		// Container child hpaned1.Gtk.Paned+PanedChild
		this.AuthorBtn = new global::Gtk.Button ();
		this.AuthorBtn.CanFocus = true;
		this.AuthorBtn.Name = "AuthorBtn";
		this.AuthorBtn.UseUnderline = true;
		this.AuthorBtn.Label = global::Mono.Unix.Catalog.GetString ("Author");
		this.hpaned1.Add (this.AuthorBtn);
		this.vbox1.Add (this.hpaned1);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hpaned1]));
		w7.Position = 2;
		w7.Expand = false;
		w7.Fill = false;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 772;
		this.DefaultHeight = 646;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.refreshAction.Activated += new global::System.EventHandler (this.FetchFromNet);
		this.AuthorBtn.Clicked += new global::System.EventHandler (this.AuthorClicked);
	}
}
